import Config
config :deerbot,
  discord_token: System.get_env("DEERBOT_DISCORD_TOKEN"),
  reaction_phrase: "ｼｶｯｼｶｯ",
  reaction_emoji: "🦌",
  repo_url: "https://github.com/Hitomaru/deerbot",
  foods: [
    "寿司",
    "天丼",
    "カレー",
    "中華料理",
    "ハンバーガー",
    "パスタ",
    "焼肉",
    "焼き魚",
    "オムレツ",
    "炒飯",
    "定食",
    "ステーキ",
    "ハンバーグ",
    "タイ料理",
    "つけ麺",
    "油そば",
    "フランス料理"
  ]
